# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dthing_remote.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from UI.Edit import IPEdit

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 400)
        MainWindow.setMaximumSize(QtCore.QSize(850, 450))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidget.setContentsMargins(10, 10,10, 10)
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btnCurrentConnection = QtWidgets.QPushButton(self.tab)
        self.btnCurrentConnection.setObjectName("btnCurrentConnection")
        self.horizontalLayout_7.addWidget(self.btnCurrentConnection)
        self.textCurrentConnectionNum = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textCurrentConnectionNum.sizePolicy().hasHeightForWidth())
        self.textCurrentConnectionNum.setSizePolicy(sizePolicy)
        self.textCurrentConnectionNum.setMinimumSize(QtCore.QSize(25, 25))
        self.textCurrentConnectionNum.setMaximumSize(QtCore.QSize(25, 25))
        self.textCurrentConnectionNum.setFrame(False)
        self.textCurrentConnectionNum.setAlignment(QtCore.Qt.AlignCenter)
        self.textCurrentConnectionNum.setReadOnly(True)
        self.textCurrentConnectionNum.setObjectName("textCurrentConnectionNum")
        self.horizontalLayout_7.addWidget(self.textCurrentConnectionNum)
        self.gridLayout.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setMinimumSize(QtCore.QSize(450, 250))
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 1, 7, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnActivateConnection = QtWidgets.QPushButton(self.tab)
        self.btnActivateConnection.setObjectName("btnActivateConnection")
        self.horizontalLayout.addWidget(self.btnActivateConnection)
        self.textActivateConnectionNum = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textActivateConnectionNum.sizePolicy().hasHeightForWidth())
        self.textActivateConnectionNum.setSizePolicy(sizePolicy)
        self.textActivateConnectionNum.setMaximumSize(QtCore.QSize(25, 25))
        self.textActivateConnectionNum.setAlignment(QtCore.Qt.AlignCenter)
        self.textActivateConnectionNum.setObjectName("textActivateConnectionNum")
        self.horizontalLayout.addWidget(self.textActivateConnectionNum)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.textCurrentConnection = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textCurrentConnection.sizePolicy().hasHeightForWidth())
        self.textCurrentConnection.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(True)
        self.textCurrentConnection.setFont(font)
        self.textCurrentConnection.setAutoFillBackground(False)
        self.textCurrentConnection.setAlignment(QtCore.Qt.AlignCenter)
        self.textCurrentConnection.setIndent(-1)
        self.textCurrentConnection.setObjectName("textCurrentConnection")
        self.gridLayout.addWidget(self.textCurrentConnection, 2, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btnList = QtWidgets.QPushButton(self.tab)
        self.btnList.setObjectName("btnList")
        self.horizontalLayout_8.addWidget(self.btnList)
        self.textListNum = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textListNum.sizePolicy().hasHeightForWidth())
        self.textListNum.setSizePolicy(sizePolicy)
        self.textListNum.setMinimumSize(QtCore.QSize(25, 25))
        self.textListNum.setMaximumSize(QtCore.QSize(25, 25))
        self.textListNum.setFrame(False)
        self.textListNum.setAlignment(QtCore.Qt.AlignCenter)
        self.textListNum.setReadOnly(True)
        self.textListNum.setObjectName("textListNum")
        self.horizontalLayout_8.addWidget(self.textListNum)
        self.gridLayout.addLayout(self.horizontalLayout_8, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnRun = QtWidgets.QPushButton(self.tab)
        self.btnRun.setObjectName("btnRun")
        self.horizontalLayout_2.addWidget(self.btnRun)
        self.textRunNum = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textRunNum.sizePolicy().hasHeightForWidth())
        self.textRunNum.setSizePolicy(sizePolicy)
        self.textRunNum.setMaximumSize(QtCore.QSize(25, 25))
        self.textRunNum.setAlignment(QtCore.Qt.AlignCenter)
        self.textRunNum.setObjectName("textRunNum")
        self.horizontalLayout_2.addWidget(self.textRunNum)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnStop = QtWidgets.QPushButton(self.tab)
        self.btnStop.setObjectName("btnStop")
        self.horizontalLayout_3.addWidget(self.btnStop)
        self.textStopNum = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textStopNum.sizePolicy().hasHeightForWidth())
        self.textStopNum.setSizePolicy(sizePolicy)
        self.textStopNum.setMaximumSize(QtCore.QSize(25, 25))
        self.textStopNum.setAlignment(QtCore.Qt.AlignCenter)
        self.textStopNum.setObjectName("textStopNum")
        self.horizontalLayout_3.addWidget(self.textStopNum)
        self.gridLayout.addLayout(self.horizontalLayout_3, 5, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnDelete = QtWidgets.QPushButton(self.tab)
        self.btnDelete.setObjectName("btnDelete")
        self.horizontalLayout_4.addWidget(self.btnDelete)
        self.textDeleteNum = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textDeleteNum.sizePolicy().hasHeightForWidth())
        self.textDeleteNum.setSizePolicy(sizePolicy)
        self.textDeleteNum.setMinimumSize(QtCore.QSize(25, 25))
        self.textDeleteNum.setMaximumSize(QtCore.QSize(25, 25))
        self.textDeleteNum.setAlignment(QtCore.Qt.AlignCenter)
        self.textDeleteNum.setObjectName("textDeleteNum")
        self.horizontalLayout_4.addWidget(self.textDeleteNum)
        self.gridLayout.addLayout(self.horizontalLayout_4, 6, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.btnDownLoad = QtWidgets.QPushButton(self.tab)
        self.btnDownLoad.setObjectName("btnDownLoad")
        self.horizontalLayout_13.addWidget(self.btnDownLoad)
        self.textDownloadUrl = QtWidgets.QTextEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textDownloadUrl.sizePolicy().hasHeightForWidth())
        self.textDownloadUrl.setSizePolicy(sizePolicy)
        self.textDownloadUrl.setMaximumSize(QtCore.QSize(16777215, 25))
        self.textDownloadUrl.setObjectName("textDownloadUrl")
        self.horizontalLayout_13.addWidget(self.textDownloadUrl)
        self.gridLayout.addLayout(self.horizontalLayout_13, 7, 0, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_15.addWidget(self.label_10)
        self.textMemoryStatus = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textMemoryStatus.sizePolicy().hasHeightForWidth())
        self.textMemoryStatus.setSizePolicy(sizePolicy)
        self.textMemoryStatus.setMinimumSize(QtCore.QSize(75, 25))
        self.textMemoryStatus.setMaximumSize(QtCore.QSize(75, 25))
        self.textMemoryStatus.setFrame(False)
        self.textMemoryStatus.setReadOnly(True)
        self.textMemoryStatus.setObjectName("textMemoryStatus")
        self.horizontalLayout_15.addWidget(self.textMemoryStatus)
        self.gridLayout_2.addLayout(self.horizontalLayout_15, 0, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_14.addWidget(self.label_9)
        self.textOutmemoryStatus = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textOutmemoryStatus.sizePolicy().hasHeightForWidth())
        self.textOutmemoryStatus.setSizePolicy(sizePolicy)
        self.textOutmemoryStatus.setMinimumSize(QtCore.QSize(75, 25))
        self.textOutmemoryStatus.setMaximumSize(QtCore.QSize(75, 25))
        self.textOutmemoryStatus.setFrame(False)
        self.textOutmemoryStatus.setReadOnly(True)
        self.textOutmemoryStatus.setObjectName("textOutmemoryStatus")
        self.horizontalLayout_14.addWidget(self.textOutmemoryStatus)
        self.gridLayout_2.addLayout(self.horizontalLayout_14, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.textCpuUsedRate = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textCpuUsedRate.sizePolicy().hasHeightForWidth())
        self.textCpuUsedRate.setSizePolicy(sizePolicy)
        self.textCpuUsedRate.setMinimumSize(QtCore.QSize(75, 25))
        self.textCpuUsedRate.setMaximumSize(QtCore.QSize(75, 25))
        self.textCpuUsedRate.setFrame(False)
        self.textCpuUsedRate.setReadOnly(True)
        self.textCpuUsedRate.setObjectName("textCpuUsedRate")
        self.horizontalLayout_6.addWidget(self.textCpuUsedRate)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 2, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_9.addWidget(self.label_3)
        self.textCpuTemp = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textCpuTemp.sizePolicy().hasHeightForWidth())
        self.textCpuTemp.setSizePolicy(sizePolicy)
        self.textCpuTemp.setMinimumSize(QtCore.QSize(75, 25))
        self.textCpuTemp.setMaximumSize(QtCore.QSize(75, 25))
        self.textCpuTemp.setFrame(False)
        self.textCpuTemp.setReadOnly(True)
        self.textCpuTemp.setObjectName("textCpuTemp")
        self.horizontalLayout_9.addWidget(self.textCpuTemp)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 3, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4)
        self.textCpuVoletage = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textCpuVoletage.sizePolicy().hasHeightForWidth())
        self.textCpuVoletage.setSizePolicy(sizePolicy)
        self.textCpuVoletage.setMinimumSize(QtCore.QSize(75, 25))
        self.textCpuVoletage.setMaximumSize(QtCore.QSize(75, 25))
        self.textCpuVoletage.setFrame(False)
        self.textCpuVoletage.setReadOnly(True)
        self.textCpuVoletage.setObjectName("textCpuVoletage")
        self.horizontalLayout_10.addWidget(self.textCpuVoletage)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 4, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_11.addWidget(self.label_5)
        self.textUsedMemoryRate = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textUsedMemoryRate.sizePolicy().hasHeightForWidth())
        self.textUsedMemoryRate.setSizePolicy(sizePolicy)
        self.textUsedMemoryRate.setMinimumSize(QtCore.QSize(75, 25))
        self.textUsedMemoryRate.setMaximumSize(QtCore.QSize(75, 25))
        self.textUsedMemoryRate.setFrame(False)
        self.textUsedMemoryRate.setReadOnly(True)
        self.textUsedMemoryRate.setObjectName("textUsedMemoryRate")
        self.horizontalLayout_11.addWidget(self.textUsedMemoryRate)
        self.gridLayout_2.addLayout(self.horizontalLayout_11, 5, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.textUsedMemory = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textUsedMemory.sizePolicy().hasHeightForWidth())
        self.textUsedMemory.setSizePolicy(sizePolicy)
        self.textUsedMemory.setMinimumSize(QtCore.QSize(75, 25))
        self.textUsedMemory.setMaximumSize(QtCore.QSize(75, 25))
        self.textUsedMemory.setFrame(False)
        self.textUsedMemory.setReadOnly(True)
        self.textUsedMemory.setObjectName("textUsedMemory")
        self.horizontalLayout_5.addWidget(self.textUsedMemory)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 6, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_12.addWidget(self.label_6)
        self.textUnUsedMemory = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textUnUsedMemory.sizePolicy().hasHeightForWidth())
        self.textUnUsedMemory.setSizePolicy(sizePolicy)
        self.textUnUsedMemory.setMinimumSize(QtCore.QSize(75, 25))
        self.textUnUsedMemory.setMaximumSize(QtCore.QSize(75, 25))
        self.textUnUsedMemory.setFrame(False)
        self.textUnUsedMemory.setReadOnly(True)
        self.textUnUsedMemory.setObjectName("textUnUsedMemory")
        self.horizontalLayout_12.addWidget(self.textUnUsedMemory)
        self.gridLayout_2.addLayout(self.horizontalLayout_12, 7, 0, 1, 1)
        self.label_9.raise_()
        self.gridLayout_5.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidget = QtWidgets.QTableView(self.groupBox_2)
        self.tableWidget.setMinimumSize(QtCore.QSize(450, 0))
        self.tableWidget.setObjectName("tableWidget")
        self.gridLayout_4.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_16.addWidget(self.label_7)
        self.textGpsJ = QtWidgets.QLineEdit(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textGpsJ.sizePolicy().hasHeightForWidth())
        self.textGpsJ.setSizePolicy(sizePolicy)
        self.textGpsJ.setMinimumSize(QtCore.QSize(150, 25))
        self.textGpsJ.setMaximumSize(QtCore.QSize(65535, 25))
        self.textGpsJ.setFrame(False)
        self.textGpsJ.setReadOnly(True)
        self.textGpsJ.setObjectName("textGpsJ")
        self.horizontalLayout_16.addWidget(self.textGpsJ)
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_16.addWidget(self.label_8)
        self.textGpsW = QtWidgets.QLineEdit(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textGpsW.sizePolicy().hasHeightForWidth())
        self.textGpsW.setSizePolicy(sizePolicy)
        self.textGpsW.setMinimumSize(QtCore.QSize(150, 25))
        self.textGpsW.setMaximumSize(QtCore.QSize(65535, 25))
        self.textGpsW.setFrame(False)
        self.textGpsW.setReadOnly(True)
        self.textGpsW.setObjectName("textGpsW")
        self.horizontalLayout_16.addWidget(self.textGpsW)
        self.gridLayout_5.addLayout(self.horizontalLayout_16, 1, 0, 1, 2)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_17.addWidget(self.label_14)
        self.lineEdit = IPEdit(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(25, 25))
        self.lineEdit.setMaximumSize(QtCore.QSize(25, 25))
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_17.addWidget(self.lineEdit)
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_17.addWidget(self.label_11)
        self.lineEdit_2 = IPEdit(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(25, 25))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(25, 25))
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_17.addWidget(self.lineEdit_2)
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_17.addWidget(self.label_12)
        self.lineEdit_3 = IPEdit(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(25, 25))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(25, 25))
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_17.addWidget(self.lineEdit_3)
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_17.addWidget(self.label_13)
        self.lineEdit_4 = IPEdit(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(25, 25))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(25, 25))
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_17.addWidget(self.lineEdit_4)
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(45, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_17.addWidget(self.pushButton)
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_17.addWidget(self.label_15)
        self.gridLayout_5.addLayout(self.horizontalLayout_17, 2, 0, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.btnDownLoad.raise_()
        self.textDownloadUrl.raise_()
        self.label_8.raise_()
        self.label_7.raise_()
        self.tabWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCmdHelp = QtWidgets.QAction(MainWindow)
        self.actionCmdHelp.setIcon(QtGui.QIcon(':about.ico'))
        self.actionCmdHelp.setObjectName("actionCmdHelp")
        self.actionCleanLog = QtWidgets.QAction(MainWindow)
        self.actionCleanLog.setIcon(QtGui.QIcon(':clean.ico'))
        self.actionCleanLog.setObjectName("actionCleanLog")
        self.actionSoftInfo = QtWidgets.QAction(MainWindow)
        self.actionSoftInfo.setIcon(QtGui.QIcon(':about.ico'))
        self.actionSoftInfo.setObjectName("actionSoftInfo")
        self.actionVisitUs = QtWidgets.QAction(MainWindow)
        self.actionVisitUs.setIcon(QtGui.QIcon(':visit.ico'))
        self.actionVisitUs.setObjectName("actionVisitUs")
        self.actionImportCfg = QtWidgets.QAction(MainWindow)
        self.actionImportCfg.setIcon(QtGui.QIcon(':file.ico'))
        self.actionImportCfg.setObjectName("actionImportCfg")
        self.menu.addAction(self.actionImportCfg)
        self.menu_2.addAction(self.actionCmdHelp)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.actionCleanLog)
        self.menu_3.addAction(self.actionSoftInfo)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.actionVisitUs)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DTU远程工具"))
        self.btnCurrentConnection.setText(_translate("MainWindow", "当前连接"))
        self.textCurrentConnectionNum.setText(_translate("MainWindow", "0"))
        self.btnActivateConnection.setText(_translate("MainWindow", "激活连接"))
        self.textCurrentConnection.setText(_translate("MainWindow", "未有连接激活"))
        self.btnList.setText(_translate("MainWindow", "应用列表"))
        self.textListNum.setText(_translate("MainWindow", "0"))
        self.btnRun.setText(_translate("MainWindow", "运行应用"))
        self.btnStop.setText(_translate("MainWindow", "停止应用"))
        self.btnDelete.setText(_translate("MainWindow", "删除应用"))
        self.btnDownLoad.setText(_translate("MainWindow", "远程下载"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Dthing远程"))
        self.groupBox.setTitle(_translate("MainWindow", "系统参数"))
        self.label_10.setText(_translate("MainWindow", "内存状态："))
        self.label_9.setText(_translate("MainWindow", "外存状态："))
        self.label_2.setText(_translate("MainWindow", "CPU使用率："))
        self.label_3.setText(_translate("MainWindow", "CPU温度值："))
        self.label_4.setText(_translate("MainWindow", "CPU电压值："))
        self.label_5.setText(_translate("MainWindow", "内存使用率："))
        self.label.setText(_translate("MainWindow", "已使用内存："))
        self.label_6.setText(_translate("MainWindow", "未使用内存："))
        self.groupBox_2.setTitle(_translate("MainWindow", "进程管理"))
        self.label_7.setText(_translate("MainWindow", "GPS经度："))
        self.label_8.setText(_translate("MainWindow", "GPS纬度："))
        self.label_14.setText(_translate("MainWindow", "DTU地址："))
        self.label_11.setText(_translate("MainWindow", "."))
        self.label_12.setText(_translate("MainWindow", "."))
        self.label_13.setText(_translate("MainWindow", "."))
        self.pushButton.setText(_translate("MainWindow", "查 看"))
        self.label_15.setText(_translate("MainWindow", " "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "系统管理"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "帮助"))
        self.menu_3.setTitle(_translate("MainWindow", "关于"))
        self.actionCmdHelp.setText(_translate("MainWindow", "查看命令"))
        self.actionCleanLog.setText(_translate("MainWindow", "清除日志"))
        self.actionSoftInfo.setText(_translate("MainWindow", "软件信息"))
        self.actionVisitUs.setText(_translate("MainWindow", "访问我们"))
        self.actionImportCfg.setText(_translate("MainWindow", "导入配置"))

