# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dtu_simulator2.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from UI.CheckedComboBox import CheckedComboBox
from Ico import ico

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(698, 450)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboProject = CheckedComboBox(self.centralwidget)
        self.comboProject.setMinimumSize(QtCore.QSize(150, 0))
        self.comboProject.setObjectName("comboProject")
        self.gridLayout.addWidget(self.comboProject, 0, 1, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setMinimumSize(QtCore.QSize(700, 400))
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 2, 7, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboData = CheckedComboBox(self.centralwidget)
        self.comboData.setObjectName("comboData")
        self.gridLayout.addWidget(self.comboData, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 5))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rdoNumLess = QtWidgets.QRadioButton(self.groupBox)
        self.rdoNumLess.setChecked(True)
        self.rdoNumLess.setObjectName("rdoNumLess")
        self.horizontalLayout_2.addWidget(self.rdoNumLess)
        self.rdoNumNormal = QtWidgets.QRadioButton(self.groupBox)
        self.rdoNumNormal.setObjectName("rdoNumNormal")
        self.horizontalLayout_2.addWidget(self.rdoNumNormal)
        self.rdoNumMuch = QtWidgets.QRadioButton(self.groupBox)
        self.rdoNumMuch.setObjectName("rdoNumMuch")
        self.horizontalLayout_2.addWidget(self.rdoNumMuch)
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.rdoStady = QtWidgets.QRadioButton(self.groupBox_2)
        self.rdoStady.setChecked(True)
        self.rdoStady.setObjectName("rdoStady")
        self.horizontalLayout_3.addWidget(self.rdoStady)
        self.rdoNormal = QtWidgets.QRadioButton(self.groupBox_2)
        self.rdoNormal.setObjectName("rdoNormal")
        self.horizontalLayout_3.addWidget(self.rdoNormal)
        self.rdoRestady = QtWidgets.QRadioButton(self.groupBox_2)
        self.rdoRestady.setObjectName("rdoRestady")
        self.horizontalLayout_3.addWidget(self.rdoRestady)
        self.gridLayout.addWidget(self.groupBox_2, 4, 0, 1, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.rdoLessExcep = QtWidgets.QRadioButton(self.groupBox_3)
        self.rdoLessExcep.setChecked(True)
        self.rdoLessExcep.setObjectName("rdoLessExcep")
        self.horizontalLayout_4.addWidget(self.rdoLessExcep)
        self.rdoNormalExcep = QtWidgets.QRadioButton(self.groupBox_3)
        self.rdoNormalExcep.setObjectName("rdoNormalExcep")
        self.horizontalLayout_4.addWidget(self.rdoNormalExcep)
        self.rdoHighExcep = QtWidgets.QRadioButton(self.groupBox_3)
        self.rdoHighExcep.setObjectName("rdoHighExcep")
        self.horizontalLayout_4.addWidget(self.rdoHighExcep)
        self.gridLayout.addWidget(self.groupBox_3, 5, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.btnStart = QtWidgets.QPushButton(self.centralwidget)
        self.btnStart.setObjectName("btnStart")
        self.horizontalLayout.addWidget(self.btnStart)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.gridLayout.addLayout(self.horizontalLayout, 6, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 698, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setIcon(QtGui.QIcon(':about.ico'))
        self.action.setObjectName("action")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_3.setIcon(QtGui.QIcon(':visit.ico'))
        self.action_import = QtWidgets.QAction(MainWindow)
        self.action_import.setIcon(QtGui.QIcon(':file.ico'))
        self.action_import.setObjectName("action_import")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_4.setIcon(QtGui.QIcon(':clean.ico'))
        self.menu.addAction(self.action_import)
        self.menu_2.addAction(self.action)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action_3)
        self.menu_3.addAction(self.action_4)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        MainWindow.setWindowIcon(QtGui.QIcon(':logo.ico'))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DTU模拟器2.0"))
        self.label.setText(_translate("MainWindow", " 项 目"))
        self.label_2.setText(_translate("MainWindow", " 数 据"))
        self.groupBox.setTitle(_translate("MainWindow", "DTU数量设置"))
        self.rdoNumLess.setText(_translate("MainWindow", "少量"))
        self.rdoNumNormal.setText(_translate("MainWindow", "适量"))
        self.rdoNumMuch.setText(_translate("MainWindow", "大量"))
        self.groupBox_2.setTitle(_translate("MainWindow", "DTU性能设置"))
        self.rdoStady.setText(_translate("MainWindow", "稳定"))
        self.rdoNormal.setText(_translate("MainWindow", "一般"))
        self.rdoRestady.setText(_translate("MainWindow", "不稳定"))
        self.groupBox_3.setTitle(_translate("MainWindow", "数据异常设置"))
        self.rdoLessExcep.setText(_translate("MainWindow", "低异常"))
        self.rdoNormalExcep.setText(_translate("MainWindow", "一般"))
        self.rdoHighExcep.setText(_translate("MainWindow", "高异常"))
        self.btnStart.setText(_translate("MainWindow", "启  动"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "关于"))
        self.menu_3.setTitle(_translate("MainWindow", "帮助"))
        self.action.setText(_translate("MainWindow", "软件信息"))
        self.action_3.setText(_translate("MainWindow", "访问我们"))
        self.action_import.setText(_translate("MainWindow", "导入配置"))
        self.action_4.setText(_translate("MainWindow", "清除日志"))

